# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
        - image: circleci/node:13.6.0
    
    working_directory: ~/repo

    steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-

        # Install packages
        - run:
            name: install
            command: npm install

        # Save node_modules in cache
        - save_cache:
            paths:
                - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        # Lint project
        - run: 
            name: lint
            command: npm run lint
        
        # Build project
        - run:
            name: build
            command: npm run build
        
        # Run unit tests
        - run: 
            name: test
            command: npm run test